package com.free.tvtracker.utils

import com.free.tvtracker.ui.details.DetailsUiModel
import com.free.tvtracker.ui.details.DetailsUiModel.Cast
import com.free.tvtracker.ui.details.DetailsUiModel.Crew
import com.free.tvtracker.ui.details.DetailsUiModel.Season
import com.free.tvtracker.ui.details.DetailsUiModel.Video
import com.free.tvtracker.ui.details.DetailsUiModel.WatchProvider
import com.free.tvtracker.ui.details.DetailsUiModel.Watchlist

fun buildDetailsUiModel(
    tmdbId: Int = 0,
    name: String = "",
    posterUrl: String = "",
    releaseStatus: String = "",
    trackingStatus: DetailsUiModel.TrackingStatus = DetailsUiModel.TrackingStatus(null, null),
    trackingId: Int? = null,
    homepageUrl: String? = null,
    description: String? = null,
    duration: String? = null,
    genres: List<String> = emptyList(),
    seasonsInfo: String? = null,
    seasons: List<Season>? = null,
    movieSeries: DetailsUiModel.MovieSeries? = null,
    castFirst: Cast? = null,
    castSecond: Cast? = null,
    casts: List<Cast> = emptyList(),
    crew: List<Crew> = emptyList(),
    watchProviders: List<WatchProvider> = emptyList(),
    watchProvidersCountry: String = "",
    mediaTrailer: Video? = null,
    mediaVideosTrailers: List<Video> = emptyList(),
    mediaVideosTeasers: List<Video> = emptyList(),
    mediaVideosBehindTheScenes: List<Video> = emptyList(),
    mediaVideosClipsAndOther: List<Video> = emptyList(),
    mediaMostPopularImage: String? = null,
    mediaImagesPosters: List<String> = emptyList(),
    mediaImagesBackdrops: List<String> = emptyList(),
    ratingTmdbVoteAverage: String = "",
    ratingTmdbVoteCount: String = "",
    omdbRatings: DetailsUiModel.Ratings? = null,
    reviews: DetailsUiModel.Reviews? = null,
    isTvShow: Boolean = true,
    budget: String = "",
    revenue: String = "",
    website: String = "",
    watchlists: List<Watchlist> = emptyList(),
    watchlisted: Boolean = false,
    isFinished: Boolean = false,
    isWatching: Boolean = false,
) = DetailsUiModel(
    isTvShow = isTvShow,
    tmdbId = tmdbId,
    name = name,
    posterUrl = posterUrl,
    releaseStatus = releaseStatus,
    duration = duration,
    trackingStatus = trackingStatus,
    trackedContentId = trackingId,
    homepageUrl = homepageUrl,
    description = description,
    genres = genres,
    seasonsInfo = seasonsInfo,
    seasons = seasons,
    movieSeries = movieSeries,
    castFirst = castFirst,
    castSecond = castSecond,
    cast = casts,
    watchProviders = watchProviders,
    crew = crew,
    watchProviderCountry = watchProvidersCountry,
    mediaTrailer = mediaTrailer,
    mediaVideosTrailers = mediaVideosTrailers,
    mediaVideosTeasers = mediaVideosTeasers,
    mediaVideosBehindTheScenes = mediaVideosBehindTheScenes,
    mediaMostPopularImage = mediaMostPopularImage,
    mediaImagesPosters = mediaImagesPosters,
    mediaImagesBackdrops = mediaImagesBackdrops,
    ratingTmdbVoteAverage = ratingTmdbVoteAverage,
    ratingTmdbVoteCount = ratingTmdbVoteCount,
    mediaVideosClipsAndOther = mediaVideosClipsAndOther,
    budget = budget,
    revenue = revenue,
    website = website,
    omdbRatings = omdbRatings,
    reviews = reviews,
    watchlists = watchlists,
    watchlisted = watchlisted,
    isFinished = isFinished,
    isWatching = isWatching
)
