create table watchlist_tracked_movies
(
    id                  integer generated by default as identity,
    created_at_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    tracked_movie_id    integer                             not null,
    watchlist_id        integer                             not null,
    primary key (id)
);
create table watchlist_tracked_shows
(
    id                  integer generated by default as identity,
    created_at_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    tracked_show_id     integer                             not null,
    watchlist_id        integer                             not null,
    primary key (id)
);
create table watchlists
(
    id                  integer generated by default as identity,
    created_at_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    name                varchar(255)                        not null,
    user_id             integer                             not null,
    primary key (id)
);
alter table if exists watchlist_tracked_movies add constraint UKtc8o9wk0ob52wyrscu1veamr unique (tracked_movie_id, watchlist_id);
alter table if exists watchlist_tracked_shows add constraint UKbsev7mrfr4hmnl7icssb7ug86 unique (tracked_show_id, watchlist_id);
alter table if exists watchlist_tracked_movies add constraint FKk9p5f6cmd0vdnj29y0s03hq44 foreign key (tracked_movie_id) references tracked_movies on delete cascade;
alter table if exists watchlist_tracked_movies add constraint FK2a2ecbam68dvgr5a7rgy55slt foreign key (watchlist_id) references watchlists on delete cascade;
alter table if exists watchlist_tracked_shows add constraint FKp4jx6wky9g597dv333j3kujhy foreign key (tracked_show_id) references tracked_shows on delete cascade;
alter table if exists watchlist_tracked_shows add constraint FKtj01vq2pjyawlcd74d6pmbhdw foreign key (watchlist_id) references watchlists on delete cascade;
