environment:
  mode: "production"
logging:
  file:
    path: ./logs
  level:
    com.free.tvtracker.logging.OutRequestLoggingInterceptor: OFF # keep this off, don't leak tmdb token
    com.free.tvtracker.logging.RequestLoggingInterceptor: DEBUG
    com.free.tvtracker.logging.TvtrackerLogger: ERROR
    httpclient:
      wire: OFF
    org:
      apache:
        http: DEBUG
      hibernate: OFF
      springframework:
        security: DEBUG
        web: WARN
        web.client.RestTemplate: DEBUG
    root: WARN
  threshold:
    console: trace
    file: error
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 10MB
server:
  ssl:
    enabled: false
  port: ${PORT}
spring:
  datasource:
    username: ${BOOT_DATABASE_USERNAME}
    password: ${BOOT_DATABASE_PASSWORD}
    url: ${BOOT_DATABASE_URL}
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none
    show-sql: false
sentry:
  environment: "production"
