### create anon user
POST {{host}}/user/create-anon
Content-Type: application/json

### set user credentials
POST {{host}}/user/complete-credentials
Content-Type: application/json
Authorization: Bearer {{tokenUser1}}

{
  "email": "1@test.com",
  "username": "miguel",
  "password": "password"
}

### login
POST {{host}}/user/login
Content-Type: application/json
Authorization: Bearer {{tokenUser1}}

{
  "username": "miguel",
  "password": "password"
}

### get user
GET {{host}}/user
Authorization: Bearer {{tokenUser1}}

### get trending shows
GET {{host}}/discover/trending
Authorization: Bearer {{tokenUser1}}

### get reccomended shows
GET {{host}}/discover/recommended
Authorization: Bearer {{tokenUser1}}

### get episodes from show
GET {{host}}/shows/1/episodes
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

### create tracked show
POST {{host}}/track/shows
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "tmdb_id": 12971,
  "watchlisted": false
}

### create tracked movie
POST {{host}}/track/movies
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "tmdb_id": 843214,
  "watchlisted": true
}

### search multi by term
POST {{host}}/search
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "term": "game of"
}

### add episode to tracked show
POST {{host}}/track/shows/6/episode
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "episode_ids": [
    "ed59e1a6-c465-4147-99c9-fafa3a2f02b1",
  ]
}

### get tracked shows: ongoing
GET {{host}}/track/shows/watching
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

### get tracked shows: wishlisted
GET {{host}}/track/shows/watchlist
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

### get tracked shows: finished
GET {{host}}/track/shows/finished
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

### get show by id
POST {{host}}/search/show
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "tmdb_id": "1399"
}

### get recommended
POST {{host}}/discover/recommended
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "related_shows_tmdb_ids": ["1399", "37680"]
}

### get shows with episode released soon
GET {{host}}/discover/released-soon
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

