name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Write google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123",
              "project_id": "123",
              "storage_bucket": "123.google.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:1:android:1",
                  "android_client_info": {
                    "package_name": "com.free.tvtracker"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "123"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > composeApp/google-services.json


      - name: Run tests and generate coverage
        run: ./gradlew koverXmlReport

      # Verify coverage reports exist
      - name: Check if coverage reports exist
        run: |
          ls -la composeApp/build/reports/kover/ || echo "Compose coverage report directory not found"
          ls -la server/build/reports/kover/ || echo "Server coverage report directory not found"

      # Upload both reports as artifacts (with unique names)
      - name: Upload compose coverage report to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: compose-coverage-report
          path: composeApp/build/reports/kover/report.xml
          if-no-files-found: warn

      - name: Upload server coverage report to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage-report
          path: server/build/reports/kover/report.xml
          if-no-files-found: warn

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: composeApp/build/reports/kover/report.xml,server/build/reports/kover/report.xml
          directory: ./
          flags: compose,server
          name: codecov-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
